---
title: "ml Project"
author: "Topi Sirkiä"
date: "11/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data}
npf <- read.csv("npf_train.csv") #read in data
npf <- npf[,-c(1:2,4)] # drop the id, date, partlybad columns
print(npf)
summary(npf)
```


Lets try to look at possible

```{r cars echo=FALSE results="hide" include=FALSE}
set.seed(7) 
# load caret
library(caret)
install.packages("ggplot2")

control <- trainControl(method="repeatedcv", number=10, repeats=3)
model <- train(class4~., data=npf, method="multinom", preProcess="scale", trControl=control)

importance <- data.frame(varImp(model, scale=FALSE)$importance)
importance$rows<-row.names(importance)
importance$Overall <- sort(importance$Overall, decreasing=TRUE)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
print(importance[,])
```

```{r multinom}
library(nnet) #multinomial logistic regression in nnet is used
set.seed=(6)

ttsplit <- sample(2, nrow(npf), replace= TRUE, prob=c(0.8, 0.2)) #split into test,trait data

npf_train <- npf[ttsplit==1,]
npf_test <- npf[ttsplit==2,]


#choose reference level to be noevent and train the model:
#npf$class4 <- relevel(factor(npf$class4), ref="nonevent")
model <- multinom(npf_train$class4~.,data=npf_train)

```
This summary doesnt automatically provide a z-value or p value, so it has to be done manually:
```{r ztest}
z <- summary(model)$coefficients/summary(model)$standard.error
p <- (1-pnorm(abs(z),0,1))*2 #*2 since we want 2 tailed z-test
p # we would like <0.05. not sure right now how to toss ones with p value too high
```
Another approach using recursive feature selection:
```{r}

library(mlbench)
nvars <- c(1:5,10,15,20,30,50,70) # how many predictors we want to test with

# define the control using a linear model selection function lm
control <- rfeControl(functions=lmFuncs, method="cv", number=10, verbose=FALSE)

results <- rfe(npf_train[,2:length(colnames(npf_train))],
               npf_train$class4,
               sizes=nvars,
               rfeControl=control)
# I cant see why the subscript is out of bounds
print(results)
predictors(results)

plot(results, type=c("r", "b"))
```
```{r}
dim(npf_train[,2:length(colnames(npf_train))])
length(npf_train$class4)
length(colnames(npf_train))
```


